In [4]:
import sklearn.datasets as data
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
wine = data.load_wine()

In [5]:
# Now let us convert the Data Set
df = pd.DataFrame(wine.data, columns = wine.feature_names)

In [6]:
df['wine_type'] = wine.target

In [7]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  wine_type  
0                          3.92   1065.0          0  
1                          3.40   1050.0          0  
2                          3.17   1185.0          0  
3                          3.45   1480.0          0  
4                          2.93    735.0          0

In [8]:
# Let us try to predict the Alcohol Values using Single Value
from sklearn.linear_model import LinearRegression

In [9]:
reg = LinearRegression()

In [10]:
# The variable "reg" is an instentiator 
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
x = df['proline']
y = df['alcohol']

In [12]:
x

0      1065.0
1      1050.0
2      1185.0
3      1480.0
4       735.0
5      1450.0
6      1290.0
7      1295.0
8      1045.0
9      1045.0
10     1510.0
11     1280.0
12     1320.0
13     1150.0
14     1547.0
15     1310.0
16     1280.0
17     1130.0
18     1680.0
19      845.0
20      780.0
21      770.0
22     1035.0
23     1015.0
24      845.0
25      830.0
26     1195.0
27     1285.0
28      915.0
29     1035.0
        ...  
148     650.0
149     550.0
150     500.0
151     480.0
152     425.0
153     675.0
154     640.0
155     725.0
156     480.0
157     880.0
158     660.0
159     620.0
160     520.0
161     680.0
162     570.0
163     675.0
164     615.0
165     520.0
166     695.0
167     685.0
168     750.0
169     630.0
170     510.0
171     470.0
172     660.0
173     740.0
174     750.0
175     835.0
176     840.0
177     560.0
Name: proline, Length: 178, dtype: float64

In [13]:
y

0      14.23
1      13.20
2      13.16
3      14.37
4      13.24
5      14.20
6      14.39
7      14.06
8      14.83
9      13.86
10     14.10
11     14.12
12     13.75
13     14.75
14     14.38
15     13.63
16     14.30
17     13.83
18     14.19
19     13.64
20     14.06
21     12.93
22     13.71
23     12.85
24     13.50
25     13.05
26     13.39
27     13.30
28     13.87
29     14.02
       ...  
148    13.32
149    13.08
150    13.50
151    12.79
152    13.11
153    13.23
154    12.58
155    13.17
156    13.84
157    12.45
158    14.34
159    13.48
160    12.36
161    13.69
162    12.85
163    12.96
164    13.78
165    13.73
166    13.45
167    12.82
168    13.58
169    13.40
170    12.20
171    12.77
172    14.16
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: alcohol, Length: 178, dtype: float64

In [14]:
# Since we will be using values of "x" we need it in 2D Array
x = df[['proline']]

In [15]:
x

proline
0     1065.0
1     1050.0
2     1185.0
3     1480.0
4      735.0
5     1450.0
6     1290.0
7     1295.0
8     1045.0
9     1045.0
10    1510.0
11    1280.0
12    1320.0
13    1150.0
14    1547.0
15    1310.0
16    1280.0
17    1130.0
18    1680.0
19     845.0
20     780.0
21     770.0
22    1035.0
23    1015.0
24     845.0
25     830.0
26    1195.0
27    1285.0
28     915.0
29    1035.0
..       ...
148    650.0
149    550.0
150    500.0
151    480.0
152    425.0
153    675.0
154    640.0
155    725.0
156    480.0
157    880.0
158    660.0
159    620.0
160    520.0
161    680.0
162    570.0
163    675.0
164    615.0
165    520.0
166    695.0
167    685.0
168    750.0
169    630.0
170    510.0
171    470.0
172    660.0
173    740.0
174    750.0
175    835.0
176    840.0
177    560.0

[178 rows x 1 columns]

In [16]:
#Fit linear model
reg.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
#Predict using the linear model
pred = reg.predict(x)

In [18]:
pred

array([13.52851617, 13.50362367, 13.72765619, 14.21720874, 12.98088111,
       14.16742374, 13.90190371, 13.91020121, 13.49532617, 13.49532617,
       14.26699375, 13.88530871, 13.95168872, 13.66957369, 14.32839526,
       13.93509371, 13.88530871, 13.63638368, 14.54910878, 13.16342613,
       13.05555862, 13.03896362, 13.47873117, 13.44554116, 13.16342613,
       13.13853363, 13.74425119, 13.89360621, 13.27959114, 13.47873117,
       13.89360621, 14.27529125, 13.40405366, 13.8106312 , 13.57830118,
       13.28788865, 13.22150864, 13.59489618, 13.45383866, 13.02236862,
       13.08045112, 13.47873117, 13.57830118, 12.8896086 , 13.22980614,
       13.55340867, 13.52851617, 13.39575616, 13.52021867, 13.85211871,
       13.66957369, 13.86041621, 13.73595369, 14.04296123, 13.52021867,
       13.61978868, 13.37086365, 13.86871371, 13.89360621, 12.62408858,
       12.8896086 , 12.50792356, 12.80663359, 12.45813856, 12.35027105,
       12.8862896 , 12.59421757, 12.60749357, 13.00577362, 12.95

In [19]:
from sklearn import metrics
#module includes score functions, performance metrics 
#and pairwise metrics and distance computations.

In [20]:
#Calculate R-Squared Value
metrics.r2_score(y, pred)

0.4143754862647204

In [21]:
# Since we are predicting Alcohol Values, we need to drop this feature and also Wine_Type
x = df.drop(['alcohol', 'wine_type'], axis =1)

In [22]:
x

malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0          1.71  2.43               15.6      127.0           2.80   
1          1.78  2.14               11.2      100.0           2.65   
2          2.36  2.67               18.6      101.0           2.80   
3          1.95  2.50               16.8      113.0           3.85   
4          2.59  2.87               21.0      118.0           2.80   
5          1.76  2.45               15.2      112.0           3.27   
6          1.87  2.45               14.6       96.0           2.50   
7          2.15  2.61               17.6      121.0           2.60   
8          1.64  2.17               14.0       97.0           2.80   
9          1.35  2.27               16.0       98.0           2.98   
10         2.16  2.30               18.0      105.0           2.95   
11         1.48  2.32               16.8       95.0           2.20   
12         1.73  2.41               16.0       89.0           2.60   
13         1.73  2.39               11.4       91.0           3.10   
14         1.87  2.38               12.0      102.0           3.30   
15         1.81  2.70               17.2      112.0           2.85   
16         1.92  2.72               20.0      120.0           2.80   
17         1.57  2.62               20.0      115.0           2.95   
18         1.59  2.48               16.5      108.0           3.30   
19         3.10  2.56               15.2      116.0           2.70   
20         1.63  2.28               16.0      126.0           3.00   
21         3.80  2.65               18.6      102.0           2.41   
22         1.86  2.36               16.6      101.0           2.61   
23         1.60  2.52               17.8       95.0           2.48   
24         1.81  2.61               20.0       96.0           2.53   
25         2.05  3.22               25.0      124.0           2.63   
26         1.77  2.62               16.1       93.0           2.85   
27         1.72  2.14               17.0       94.0           2.40   
28         1.90  2.80               19.4      107.0           2.95   
29         1.68  2.21               16.0       96.0           2.65   
..          ...   ...                ...        ...            ...   
148        3.24  2.38               21.5       92.0           1.93   
149        3.90  2.36               21.5      113.0           1.41   
150        3.12  2.62               24.0      123.0           1.40   
151        2.67  2.48               22.0      112.0           1.48   
152        1.90  2.75               25.5      116.0           2.20   
153        3.30  2.28               18.5       98.0           1.80   
154        1.29  2.10               20.0      103.0           1.48   
155        5.19  2.32               22.0       93.0           1.74   
156        4.12  2.38               19.5       89.0           1.80   
157        3.03  2.64               27.0       97.0           1.90   
158        1.68  2.70               25.0       98.0           2.80   
159        1.67  2.64               22.5       89.0           2.60   
160        3.83  2.38               21.0       88.0           2.30   
161        3.26  2.54               20.0      107.0           1.83   
162        3.27  2.58               22.0      106.0           1.65   
163        3.45  2.35               18.5      106.0           1.39   
164        2.76  2.30               22.0       90.0           1.35   
165        4.36  2.26               22.5       88.0           1.28   
166        3.70  2.60               23.0      111.0           1.70   
167        3.37  2.30               19.5       88.0           1.48   
168        2.58  2.69               24.5      105.0           1.55   
169        4.60  2.86               25.0      112.0           1.98   
170        3.03  2.32               19.0       96.0           1.25   
171        2.39  2.28               19.5       86.0           1.39   
172        2.51  2.48               20.0       91.0           1.68   
173        5.65

In [23]:
reg.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
pred = reg.predict(x)

In [25]:
pred

array([13.66661305, 13.64752402, 13.59563623, 14.4052741 , 12.97482915,
       14.15701754, 13.85663207, 13.89779774, 13.4709283 , 13.84297084,
       14.02101275, 13.61803463, 13.82154853, 13.63461237, 14.42345393,
       14.18447268, 13.71908271, 13.60595157, 14.70283505, 13.57710193,
       13.35817881, 13.33383144, 13.41843559, 13.32366916, 13.04824697,
       12.79884478, 13.65533596, 13.45027096, 13.29175806, 13.41725635,
       13.48293341, 14.09284127, 13.11146165, 13.66649247, 13.30414209,
       13.24784155, 13.30314255, 13.29265567, 13.18334915, 13.63423042,
       13.32684749, 13.458762  , 13.77941017, 13.15429841, 13.21852136,
       13.82152627, 13.72213254, 13.53142533, 13.46094036, 14.2264349 ,
       13.85794468, 13.76673994, 14.09331536, 14.03032453, 13.59846737,
       13.48538009, 13.58934323, 13.89144957, 13.90264255, 12.33551952,
       12.61359476, 12.67111418, 12.69102457, 12.56493353, 12.27242088,
       12.72326328, 12.78345378, 12.74724228, 12.65455758, 12.49

In [26]:
metrics.r2_score(y, pred)

0.5935573146395274

In [28]:
# Let us learn about our Classification by using Logistic Regression
# In Logistic Regression the values remain between 0 and 1
# Binary dependent variable, can be extended to predict outputs with more than 2 variables
# This is also called GLM (Generalized Linear Models)

In [29]:
# Let us Predict Wine_Type

In [30]:
x = df.drop('wine_type', axis=1)
y = df ['wine_type']

In [31]:
from sklearn.linear_model import LogisticRegression

In [33]:
clf = LogisticRegression()
clf

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [34]:
clf.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
pred = clf.predict(x)

In [36]:
pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [37]:
metrics.accuracy_score(y, pred)

0.9719101123595506

In [38]:
# This is very near to 1, and looks excellent as it is 97%

In [39]:
# Now let us see, what happens when we use two columns
x = df[['proline']]
y = df ['wine_type']

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
clf = LogisticRegression()
clf

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [42]:
clf.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
pred = clf.predict(x)

In [49]:
pred

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1])

In [44]:
metrics.accuracy_score(y, pred)

0.6853932584269663

In [46]:
# For "proline" the prediction is 69%