In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn.datasets as data

In [3]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

In [4]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [5]:
# What is the difference here?
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [6]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [7]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
# It is a two dimensional array

In [9]:
# How to select one or more elements in a vector or matrix.
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [10]:
# Now select third element of vector...
# Hint: NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1.

In [11]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [12]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [14]:
# Select the last element
vector[-1]

6

In [15]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [16]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [17]:
# Describing a Matrix
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [25]:
# View number of rows and columns
matrix.shape

(3, 4)

In [26]:
# View number of elements (rows * columns)
matrix.size

12

In [27]:
# View number of dimensions
matrix.ndim

2

In [12]:
# Let's create a Sparse Matrix
from scipy import sparse

In [13]:
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

In [14]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [15]:
# Amazon Prime is an example, where we have shows, movies and viewers either watching or not watching...
# This matrix would have tens of thousands of columns and millions of rows! 
# However, since most users do not watch most movies, the vast majority of elements would be zero.

In [16]:
# View sparse matrixprint(matrix_sparse)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [28]:
# How to apply Lambda Function on your data set
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [32]:
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [33]:
# Or we can simply add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [34]:
# Return maximum element
np.max(matrix)

9

In [1]:
# Now return minumum element
np.min(matrix)

NameError: name 'np' is not defined

In [36]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [37]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [38]:
# Return mean
np.mean(matrix)

5.0

In [39]:
# Return variance
np.var(matrix)

6.666666666666667

In [40]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [41]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [4]:
wine = data.load_wine()

In [3]:
wine

NameError: name 'wine' is not defined

In [22]:
type(wine)

sklearn.utils.Bunch

In [23]:
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [24]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [25]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [26]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [5]:
# Now let us convert the Data Set
df = pd.DataFrame(wine.data, columns = wine.feature_names)

In [28]:
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [29]:
# Let us see the Catagorical Variable (Wine Types)
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [30]:
df['wine_type'] = wine.target

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
alcohol                         178 non-null float64
malic_acid                      178 non-null float64
ash                             178 non-null float64
alcalinity_of_ash               178 non-null float64
magnesium                       178 non-null float64
total_phenols                   178 non-null float64
flavanoids                      178 non-null float64
nonflavanoid_phenols            178 non-null float64
proanthocyanins                 178 non-null float64
color_intensity                 178 non-null float64
hue                             178 non-null float64
od280/od315_of_diluted_wines    178 non-null float64
proline                         178 non-null float64
dtypes: float64(13)
memory usage: 18.2 KB


In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression()


In [14]:
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
x = df(['praline'])
y = df(['alcohol'])

TypeError: 'DataFrame' object is not callable

In [37]:
x

0      1065.0
1      1050.0
2      1185.0
3      1480.0
4       735.0
        ...  
173     740.0
174     750.0
175     835.0
176     840.0
177     560.0
Name: proline, Length: 178, dtype: float64

In [25]:
reg.fit(x, y)

ValueError: Expected 2D array, got 1D array instead:
array=[1065. 1050. 1185. 1480.  735. 1450. 1290. 1295. 1045. 1045. 1510. 1280.
 1320. 1150. 1547. 1310. 1280. 1130. 1680.  845.  780.  770. 1035. 1015.
  845.  830. 1195. 1285.  915. 1035. 1285. 1515.  990. 1235. 1095.  920.
  880. 1105. 1020.  760.  795. 1035. 1095.  680.  885. 1080. 1065.  985.
 1060. 1260. 1150. 1265. 1190. 1375. 1060. 1120.  970. 1270. 1285.  520.
  680.  450.  630.  420.  355.  678.  502.  510.  750.  718.  870.  410.
  472.  985.  886.  428.  392.  500.  750.  463.  278.  714.  630.  515.
  520.  450.  495.  562.  680.  625.  480.  450.  495.  290.  345.  937.
  625.  428.  660.  406.  710.  562.  438.  415.  672.  315.  510.  488.
  312.  680.  562.  325.  607.  434.  385.  407.  495.  345.  372.  564.
  625.  465.  365.  380.  380.  378.  352.  466.  342.  580.  630.  530.
  560.  600.  650.  695.  720.  515.  580.  590.  600.  780.  520.  550.
  855.  830.  415.  625.  650.  550.  500.  480.  425.  675.  640.  725.
  480.  880.  660.  620.  520.  680.  570.  675.  615.  520.  695.  685.
  750.  630.  510.  470.  660.  740.  750.  835.  840.  560.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [35]:
pred = reg.predict(x)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [33]:
pred

NameError: name 'pred' is not defined

In [34]:
from sklearn import metrics

In [29]:
metrics.r2_score(y, pred)

NameError: name 'pred' is not defined

In [1]:
x = df.drop(['alcohol', 'wine_type'], axis = 1)

NameError: name 'df' is not defined

In [2]:
reg.fit(x, y)

NameError: name 'reg' is not defined

In [3]:
pred = reg.predit(x)

NameError: name 'reg' is not defined

In [ ]:
pred
