In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn.datasets as data

In [6]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

In [7]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [8]:
# What is the difference here?
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [9]:
# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [10]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [11]:
# It is a two dimensional array

In [17]:
# How to select one or more elements in a vector or matrix.
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
# Now select third element of vector...
# Hint: NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1.

In [18]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [19]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [20]:
# Select the last element
vector[-1]

6

In [3]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [4]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [24]:
# Describing a Matrix
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [25]:
# View number of rows and columns
matrix.shape

(3, 4)

In [26]:
# View number of elements (rows * columns)
matrix.size

12

In [27]:
# View number of dimensions
matrix.ndim

2

In [12]:
# Let's create a Sparse Matrix
from scipy import sparse

In [13]:
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

In [14]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [15]:
# Amazon Prime is an example, where we have shows, movies and viewers either watching or not watching...
# This matrix would have tens of thousands of columns and millions of rows! 
# However, since most users do not watch most movies, the vast majority of elements would be zero.

In [16]:
# View sparse matrix print(matrix_sparse)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [28]:
# How to apply Lambda Function on your data set
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [32]:
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [33]:
# Or we can simply add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [34]:
# Return maximum element
np.max(matrix)

9

In [5]:
# Now return minumum element
np.min(matrix)

1

In [36]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [37]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [38]:
# Return mean
np.mean(matrix)

5.0

In [39]:
# Return variance
np.var(matrix)

6.666666666666667

In [40]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [41]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])